spring:
  application:
    name: sec-jwt
  profiles:
    # 새로운 파일이 생길 때 여기에 추가
    active: dev,db,auth
---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:.env[.properties]
  thymeleaf:
    cache: false
