spring:
  config:
    activate:
      on-profile: db
  datasource:
    url: jdbc:postgresql://${PGHOST}:5432/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update